version: "3.8"

services:
  gea-client:
    container_name: gea-client
    build:
      context: "."
      dockerfile: "Dockerfile"
    ports:
      - "80:80"
    env_file:
      - ./.env
    image: gea-client
